export const INCREMENT_SESSION = 'INCREMENT_SESSION';
export const DECREMENT_SESSION = 'DECREMENT_SESSION';

export const INCREMENT_BREAK = 'INCREMENT_BREAK';
export const DECREMENT_BREAK = 'DECREMENT_BREAK';

export const START_STOP = 'START_STOP';
export const RESET_TIMER = 'RESET_TIMER';

export const DECREMENT_TIMELEFT = 'DECREMENT_TIMELEFT';

export const TIME_OVER = 'TIME_OVER';
